# Part 3: Data Cleaning and Preprocessing
This notebook covers structural data coercion, missing value filling, engineering new metrics, and saving the cleaned snapshot.

In [32]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Data Cleaning

In [33]:
# Data Cleaning
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

print(f'Missing values before filling: \n{df.isnull().sum()}\n')
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)
df.drop("customerID",axis=1,inplace=True)

Missing values before filling:
customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

# Feature Engineering

In [34]:
# Feature Engineering
df['AverageMonthlySpend'] = df['TotalCharges'] / (df['tenure'] + 1)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,AverageMonthlySpend
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,14.925000
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,53.985714
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,36.050000
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,40.016304
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,50.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,79.620000
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,100.861644
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,28.870833
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,61.320000
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,102.156716

In [35]:
# Categorical Encoding
df['Churn'] = df['Churn'].map({'No': 0, 'Yes': 1})
df = pd.get_dummies(df, drop_first=True,dtype=int)

# Save Processed Dataset

In [36]:



output_file = "processed_telco_churn.csv"

df.to_csv(output_file, index=False)

print(f"✅ Data preprocessing completed successfully!")
print(f"📁 Processed dataset saved as: {output_file}")
print(f"📊 Dataset Shape: {df.shape}")
df

✅ Data preprocessing completed successfully!
📁 Processed dataset saved as: processed_telco_churn.csv
📊 Dataset Shape: (7043, 32)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,AverageMonthlySpend,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,14.925000,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,0,53.985714,1,0,0,1,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,36.050000,1,0,0,1,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,0,40.016304,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,1,50.550000,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,0,79.620000,1,1,1,1,...,0,1,0,1,1,0,1,0,0,1
7039,0,72,103.20,7362.90,0,100.861644,0,1,1,1,...,0,1,0,1,1,0,1,1,0,0
7040,0,11,29.60,346.45,0,28.870833,0,1,1,0,...,0,0,0,0,0,0,1,0,1,0
7041,1,4,74.40,306.60,1,61.320000,1,1,0,1,...,0,0,0,0,0,0,1,0,0,1
7042,0,66,105.65,6844.50,0,102.156716,1,0,0,1,...,0,1,0,1,0,1,1,0,0,0